---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: cinder_all
  gather_facts: false
  become: true
  tasks:
    - name: Include OSP vars
      include_vars: vars/maas-osp.yml
      when:
        - deploy_osp | bool

    - include_tasks: "common-tasks/maas_excluded_regex.yml"

    - include_tasks: "common-tasks/maas_get_openrc.yml"

    - include_tasks: "common-tasks/maas_get_maasrc.yml"

    - name: Set the current group
      set_fact:
        maas_current_group: cinder_all

  vars_files:
    - vars/main.yml
    - vars/maas.yml

  tags:
    - always


- name: Install checks for openstack cinder-api
  hosts: cinder_api
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_api_local_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_api_local_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

    - name: Install cinder lb checks
      template:
        src: "templates/rax-maas/lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_remote_check | bool
        - not maas_private_monitoring_enabled

    - name: Install cinder private lb checks
      template:
        src: "templates/rax-maas/private_lb_api_check_cinder.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/private_lb_api_check_cinder.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - maas_private_monitoring_enabled
        - maas_private_monitoring_zone is defined

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-api
  hosts: cinder_scheduler
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Install cinder api checks
      template:
        src: "templates/rax-maas/cinder_scheduler_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_scheduler_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-backup
  hosts: cinder_backup
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Install cinder backup checks
      template:
        src: "templates/rax-maas/cinder_backup_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_backup_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      delegate_to: "{{ physical_host | default(ansible_host) }}"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder


- name: Install checks for openstack cinder-volume
  hosts: cinder_volume
  gather_facts: false
  user: "{{ ansible_user | default('root') }}"
  become: true
  tasks:
    - name: Install cinder volume checks
      template:
        src: "templates/rax-maas/cinder_volume_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_volume_{{ item.key }}_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ cinder_backends | default({}) }}"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - "'volume_driver' in cinder_backends[item.key]"

    - name: Install cinder vg checks
      template:
        src: "templates/rax-maas/cinder_vg_check.yaml.j2"
        dest: "/etc/rackspace-monitoring-agent.conf.d/cinder_vg_check--{{ inventory_hostname }}.yaml"
        owner: "root"
        group: "root"
        mode: "0644"
      with_dict: "{{ cinder_backends | default({}) }}"
      delegate_to: "{{ physical_host | default(ansible_host) }}"
      when:
        - "'volume_group' in cinder_backends[item.key]"

  vars_files:
    - vars/main.yml
    - vars/maas.yml
    - vars/maas-openstack.yml

  environment: "{{ deployment_environment_variables | default({}) }}"

  tags:
    - maas-openstack-cinder
