---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- import_playbook: maas-host-private-checks.yml
  tags:
    - maas-host

- import_playbook: maas-host-cdm.yml
  tags:
    - maas-host

- import_playbook: maas-host-kernel.yml
  tags:
    - maas-host

- import_playbook: maas-host-network.yml
  tags:
    - maas-host

- import_playbook: maas-host-vendor.yml
  tags:
    - maas-host
